version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - zeladoria-net
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - zeladoria-net
      
  servicenotification:
    image: kdeluchio/servicenotification:latest
    container_name: servicenotification
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__QueueName=forgot-password
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - zeladoria-net
      
  serviceorderapi:
    image: kdeluchio/serviceorder:latest
    container_name: serviceorderapi
    ports:
      - "5011:5011"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
    networks:
      - zeladoria-net

  serviceauthapi:
    image: kdeluchio/serviceauth:latest
    container_name: serviceauthapi
    ports:
      - "5021:5021"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - zeladoria-net
      
networks:
  zeladoria-net:
    driver: bridge 