name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Testes Unitários e Integrados"]  
    types:
      - completed

jobs:
  build-and-push-serviceauth:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ServiceAuth
        uses: docker/build-push-action@v5
        with:
          context: ./ServiceAuth
          file: ./ServiceAuth/Dockerfile
          push: true
          tags: kdeluchio/serviceauth:latest

  build-and-push-servicenotification:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ServiceNotification
        uses: docker/build-push-action@v5
        with:
          context: ./ServiceNotification
          file: ./ServiceNotification/Dockerfile
          push: true
          tags: kdeluchio/servicenotification:latest

  build-and-push-serviceorder:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ServiceOrder
        uses: docker/build-push-action@v5
        with:
          context: ./ServiceOrder
          file: ./ServiceOrder/Dockerfile
          push: true
          tags: kdeluchio/serviceorder:latest